---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

  children:
    host:
      hosts:
        localhost:

    k8s_cluster:
      children:
        k8s_master:
          hosts:
            k8s-master:
              ansible_host: 10.10.10.10

        k8s_workers:
          hosts:
            k8s-worker1:
              ansible_host: 10.10.10.11
            k8s-worker2:
              ansible_host: 10.10.10.12

      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /home/gjovanov/k8s-cluster/files/ssh/k8s_ed25519
        ansible_python_interpreter: /usr/bin/python3
        ansible_become: true
        ansible_become_method: sudo
