apiVersion: apps/v1
kind: Deployment
metadata:
  name: janus
  namespace: roomler
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: janus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: janus
    spec:
      containers:
      - image: gjovanov/janus-slim:latest
        imagePullPolicy: Never
        name: janus
        ports:
        - containerPort: 8088
          name: http
          protocol: TCP
        - containerPort: 8188
          name: websocket
          protocol: TCP
        - containerPort: 7088
          name: admin-http
          protocol: TCP
        - containerPort: 7188
          name: admin-ws
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /janus/info
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
