apiVersion: v1
kind: Service
metadata:
  name: janus-nodeport
  namespace: roomler
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30808
    port: 8088
    protocol: TCP
    targetPort: 8088
  - name: websocket
    nodePort: 30818
    port: 8188
    protocol: TCP
    targetPort: 8188
  - name: admin-http
    nodePort: 30708
    port: 7088
    protocol: TCP
    targetPort: 7088
  - name: admin-ws
    nodePort: 30718
    port: 7188
    protocol: TCP
    targetPort: 7188
  selector:
    app: janus
  sessionAffinity: None
  type: NodePort
